### ISSUE TITLE
Get Dog by ID returns cropped description in response

### ISSUE THREAD

**Issue by molson82** [petfinder-com/petfinder-go-sdk#12]
When calling for a specific dog using the animal ID, it returns a JSON object with a description of the dog as the property. However, that description is cropped and not the full description.

response I'm getting from GO SDK for animal (dog) with ID of 48119604:

{
   "ID":48119604,
   "OrganizationID":"IN705",
   "URL":"https://www.petfinder.com/dog/willa-48119604/in/sellersburg/inky-animal-rescue-in705/?referrer_id=875c6437-0861-418d-a7c5-810f807e902d",
   "Type":"Dog",
   "Species":"Dog",
   "Breeds":{
      "Primary":"Chihuahua",
      "Secondary":"",
      "Mixed":true,
      "Unknown":false
   },
   "Colors":{
      "Primary":"Bicolor",
      "Secondary":"",
      "Tertiary":""
   },
   "Age":"Young",
   "Gender":"Female",
   "Size":"Small",
   "Coat":"Short",
   "Name":"Willa",
   "Description":"Willa is a chihuahua mix who spent the first two years of her life in a chicken coop, all by...",
   "Photos":[
      {
         "Small":"https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/48119604/1/?bust=1591138818\u0026width=100",
         "Medium":"https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/48119604/1/?bust=1591138818\u0026width=300",
         "Large":"https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/48119604/1/?bust=1591138818\u0026width=600",
         "Full":"https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/48119604/1/?bust=1591138818"
      }
.....
}

**Comment by ivorisoutdoors** [comment]
This is a known limitation of the public API. If you need additional access, please reach out to API support.
